### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by pgiani** [Kurounin/react-bootstrap-pagination#4]
You just need to import PropTypes

`import PropTypes from 'prop-types';`

and change the GridPaging.propType definition to:

`GridPaging.propTypes = {
  error: PropTypes.any,
  pagination: PropTypes.object,
  pageCount: PropTypes.number,
  limit: PropTypes.number,
  page: PropTypes.number,
  containerClass: PropTypes.string,
};`

**Comment by Kurounin** [comment]
Thanks for the report. I published a new version of the package with the aforementioned changes.
